// Sign In actions
export const SIGNING_IN = "SIGNING_IN"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_ERROR = "SIGN_IN_ERROR"

//Student Actions
export const RESET_STUDENT_CREATION = "RESET_STUDENT_CREATION"
export const CREATING_STUDENT = "CREATING_STUDENT"
export const CREATING_STUDENT_SUCCESS = "CREATING_STUDENT_SUCCESS"
export const CREATING_STUDENT_ERROR = "CREATING_STUDENT_ERROR"

export const RESET_STUDENT_UPDATE = "RESET_STUDENT_UPDATE"
export const UPDATING_STUDENT = "UPDATING_STUDENT"
export const UPDATING_STUDENT_SUCCESS = "UPDATING_STUDENT_SUCCESS"
export const UPDATING_STUDENT_ERROR = "UPDATING_STUDENT_ERROR"

export const RESET_STUDENT_DELETE = "RESET_STUDENT_DELETE"
export const DELETING_STUDENT = "DELETING_STUDENT"
export const DELETING_STUDENT_SUCCESS = "DELETING_STUDENT_SUCCESS"
export const DELETING_STUDENT_ERROR = "DELETING_STUDENT_ERROR"

export const RESET_GETTING_USER = "RESET_GETTING_USER"
export const GETTING_USER = "GETTING_USER"
export const GETTING_USER_SUCCESS = "GETTING_USER_SUCCESS"
export const GETTING_USER_ERROR = "GETTING_USER_ERROR"

export const LISTING_STUDENTS = "LISTING_STUDENTS"
export const LISTING_STUDENTS_SUCCESS = "LISTING_STUDENTS_SUCCESS"
export const LISTING_STUDENTS_ERROR = "LISTING_STUDENTS_ERROR"

//Staff Actions
export const RESET_STAFF_CREATION = "RESET_STAFF_CREATION"
export const CREATING_STAFF = "CREATING_STAFF"
export const CREATING_STAFF_SUCCESS = "CREATING_STAFF_SUCCESS"
export const CREATING_STAFF_ERROR = "CREATING_STAFF_ERROR"

export const RESET_STAFF_UPDATE = "RESET_STAFF_UPDATE"
export const UPDATING_STAFF = "UPDATING_STAFF"
export const UPDATING_STAFF_SUCCESS = "UPDATING_STAFF_SUCCESS"
export const UPDATING_STAFF_ERROR = "UPDATING_STAFF_ERROR"

export const RESET_STAFF_DELETE = "RESET_STAFF_DELETE"
export const DELETING_STAFF = "DELETING_STAFF"
export const DELETING_STAFF_SUCCESS = "DELETING_STAFF_SUCCESS"
export const DELETING_STAFF_ERROR = "DELETING_STAFF_ERROR"

export const RESET_GETTING_STAFF = "RESET_GETTING_STAFF"
export const GETTING_STAFF = "GETTING_STAFF"
export const GETTING_STAFF_SUCCESS = "GETTING_STAFF_SUCCESS"
export const GETTING_STAFF_ERROR = "GETTING_STAFF_ERROR"

export const LISTING_STAFFS = "LISTING_STAFFS"
export const LISTING_STAFFS_SUCCESS = "LISTING_STAFFS_SUCCESS"
export const LISTING_STAFFS_ERROR = "LISTING_STAFFS_ERROR"
